###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build webscrip image
        run: |
          docker image build -t josedembo/web_scraping:v1 .
      - name: docker run container
        run: |
          docker container run -t  -v web_scraping/dados/fornecedores:/app/dados/fornecedores josedembo/web_scraping:v1
